### ISSUE TITLE
Add missing selector constraints to the Bitwise & Power of Two co-processor

### ISSUE THREAD

**Issue by grjte** [maticnetwork/miden#206]
As pointed out by @Al-Kindi-0, it is currently possible for the prover to compute incorrect results in the bitwise operations, due to missing constraints on the operation selectors.

## Example:
I'll demonstrate this using the example from the [bitwise docs](https://maticnetwork.github.io/miden/design/aux_table/bitwise.html), which shows computation for bitwise `AND`.

Suppose that at the second row the prover sets the operation selectors for `OR` instead of for `AND`. We would end up with the following trace, which would pass the current constraints:

```
| s0  |  s1 | a     | b     | x0  | x1  | x2  | x3  | y0  | y1  | y2  | y3  | z     |
| --- | --- | ----- | ----- | --- | --- | --- | --- | --- | --- | --- | --- | ----- |
|  0  |  0  | 10    | 9     | 0   | 1   | 0   | 1   | 1   | 0   | 0   | 1   | 8     |
|  0  |  1  | 163   | 157   | 1   | 1   | 0   | 0   | 1   | 0   | 1   | 1   | 129   |
|  0  |  0  | 2615  | 2526  | 1   | 1   | 1   | 0   | 0   | 1   | 1   | 1   | 2079  |
|  0  |  0  | 41851 | 40426 | 1   | 1   | 0   | 1   | 0   | 1   | 0   | 1   | 33274 |
```

In this case, because the operation selector in the 2nd row is for `OR` instead of `AND`, the output calculated for the 3rd row is adds an `OR` over the second row, which results in 2079 instead of 2070 and leads to an incorrect result in the final row.

## Task
This task requires a few things:

- [ ] Add a failing test to the [bitwise_pow2 unit tests](https://github.com/maticnetwork/miden/blob/next/air/src/aux_table/bitwise_pow2/tests.rs) to demonstrate the issue. This can be done by manually creating a test frame with different selectors, testing against a row that is not the first row in the cycle, and asserting that enforce constraints should result in an array that is not all zeros. This can be done first as one PR.
- [ ] Define new constraints on the selectors so that they can only change at the first row of a new periodic cycle, then update the mdbook docs for the Auxiliary Table.
- [ ] Implement the new constraints in the [Bitwise & Power of Two co-processor](https://github.com/maticnetwork/miden/blob/next/air/src/aux_table/bitwise_pow2/mod.rs)

**Comment by grjte** [comment]
Note - an initial rough version of the aux table docs can be seen [here](https://hackmd.io/FN9VFzMQSMyTWv8agycccA) for reference, but I'll add them to the mdbook later today

**Comment by 0xKanekiKen** [comment]
@grjte: I'd like to take this up :)

**Comment by grjte** [comment]
Sure, I've assigned it to you. Thanks!

**Comment by grjte** [comment]
Closed by #219
